### ISSUE TITLE
Opportunity to simplify code

### ISSUE THREAD

**Issue by alex-zwingli** [Unity3dAzure/StorageServicesDemo#10]
This code beautifully uses coroutines to accomplish tasks efficiently; however, Unity provides a way to simplify this as explained [here](https://docs.unity3d.com/2017.3/Documentation/Manual/Coroutines.html). In Unity, functions with a return type of yield are assumed to be Enumerators, and these functions can be called normally instead of being called with `StartCoroutine()`. 

This comment isn't in response to any bug/failure in the code, nor does it suggest a breaking change. I just wanted to let you know about this other option.

**Comment by deadlyfingers** [comment]
@alex-zwingli great spot! I really want to avoid having to use the StartCoroutine() wrapper function for async tasks so I will certainly try to adopt this simplification.

**Comment by deadlyfingers** [comment]
@alex-zwingli although just reading through that again - is that for C# as well or just UnityScript?

**Comment by alex-zwingli** [comment]
@deadlyfingers As far as I know, this just exists within the Unity game engine.

**Comment by deadlyfingers** [comment]
Closing off as this appears to be for UnityScript unless I'm mistaken? But when .NET 4.6 support gets past experimental support stage then we should be able to use the new async await commands instead.
