### ISSUE TITLE
Uploading Asset Bundles

### ISSUE THREAD

**Issue by deadlyfingers** [Unity3dAzure/StorageServicesDemo#4]
Atm you can't officially use `StartCoroutine` in the Unity Editor to upload a bunch of Asset Bundles. Right now I'm having to use an ugly wait while workaround. 

The [Unity Roadmap](https://unity3d.com/unity/roadmap) suggests 
- AsyncOperation completion events

Expected June 2017

This should make uploading Bundles a lot easier and a much happier and responsive Editor!

**Comment by alex-zwingli** [comment]
Has this been implemented?

**Comment by deadlyfingers** [comment]
@alex-zwingli I see AsyncOperation completion was released this month. But ideally I would prefer to run the same code in Unity Editor as in Unity game without creating more code to do the same thing. So I'm thinking it might be best to remove this feature from the Editor and upload blobs using the [Azure Storage Explorer tool](https://azure.microsoft.com/en-us/features/storage-explorer/) instead which offers more features.

**Comment by deadlyfingers** [comment]
Closing... uploading with [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/) app is an easier way to upload files to blob storage.

**Comment by deadlyfingers** [comment]
![storage-explorer](https://user-images.githubusercontent.com/1880480/32448554-1c10a304-c307-11e7-8768-75343b3bb9fd.png)
