### ISSUE TITLE
Cannot Delete from Android (403 forbidden)

### ISSUE THREAD

**Issue by spaceroppa** [Unity3dAzure/StorageServicesDemo#5]
Hi David,

Firstly, excellent work and thank you for your efforts.  You have no idea how useful the work you've done with Azure Storage and Unity is!  Sadly however, I have encountered an issue while doing some testing with demo.

When used on Android, I am able to capture an image and upload it fine.  However, delete requests always return 403 Forbidden.  From my experience, this is usually because of a malformed header.  Have you, or anybody else, encountered anything similar in your testing?  Or can anybody offer any advice as to the best place to start looking for the issue?

`AndroidPlayer(ADB@127.0.0.1:34999) Response error status:Forbidden code:403 error:Response failed with status: Forbidden request url:https://mystorage.blob.core.windows.net/mycontainer/test_photo.png
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Unity3dAzure.StorageServices.RestRequest:Result(Action 1) (at C:\StorageServicesDemo-master\StorageServicesDemo-master\Assets\StorageServices\http\RestRequest.cs:141)
Unity3dAzure.StorageServices.<DeleteBlob>c__Iterator4:MoveNext() (at C:\StorageServicesDemo-master\StorageServicesDemo-master\Assets\StorageServices\blob\BlobService.cs:112)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
(Filename: C Line: 0)`

Cheers,
Roppa

**Comment by spaceroppa** [comment]
**Update**: I have tested this on iOS and it also works fine, the issue only seems to be with Android.

**Edit**: I've tried with several different versions of the Android API, all return the same result.

**Comment by deadlyfingers** [comment]
Ok, I will try to see if I can recreate the issue on Android device.

**Comment by deadlyfingers** [comment]
Unable to recreate this issue with the latest commit in master branch. Please check if problem persists with your Android device, otherwise I will close this issue.
