### ISSUE TITLE
Cannot upload asset bundle

### ISSUE THREAD

**Issue by thisislance98** [Unity3dAzure/StorageServicesDemo#6]
Whenever I try to upload an asset bundle through window -> upload asset bundles I get the error "Response failed with status: 0".  I'm not sure what this means and I'm pretty sure I've set the storage, access key, and container name correctly.

**Comment by deadlyfingers** [comment]
@thisislance98 what platform are you using Unity for Mac or Windows? Also what is your Unity version no?

**Comment by alex-zwingli** [comment]
I'm running into the same problem, but what @thisislance98 may not have noticed is that `cloud-WSA.unity3d` uploads, but the remaining two do not.

This is where it gets interesting. Clicking on
![image](https://user-images.githubusercontent.com/21690533/31835456-d44eee70-b58e-11e7-9947-c3f17e1f8f5a.png)
results in this dialog.
![image](https://user-images.githubusercontent.com/21690533/31835479-ead9aa22-b58e-11e7-9f61-cf02c14ad82c.png)

**However**, If I attach the Visual Studio 2017 debugger to Unity and go through the code while holding down F11 (the "step into" debug command), they all upload without any error.

I'm using Unity 2017.1.0f3 on Windows 10 with Creators Update.

**Comment by deadlyfingers** [comment]
Essentially the `StartCoroutine` method used for async uploading is not designed for use in the Unity Editor so I might remove this feature as discussed on [another related issue](https://github.com/Unity3dAzure/StorageServicesDemo/issues/4). The recommended way is to use [Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/) as the way to upload blobs to a container.

**Comment by deadlyfingers** [comment]
Closing... As part of the next update I'm removing the Editor upload function and replacing it with the [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/) app as the preferred option to upload blobs to Azure Storage. (Using `StartCoroutine` ended up being a bit of a hack in the Editor as it relies on being in 'play' mode to work.)
